spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ignaciospring?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: ignaciobfc98m19
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNaming.Strategy
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect